name: Sync Repositories  
  
on:  
  schedule:  
    - cron: "*/10 * * * *" # Runs every 10 minutes  
  
jobs:  
  sync-repos:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout source repository  
        uses: actions/checkout@v2  
        with:  
          repository: melilace/DatabricksPrimaryRepo  
          ref: main  
  
      - name: Add destination repository as remote  
        run: |  
          git remote add destination 'https://github.com/melilace/DatabricksSecondaryRepo.git'
          git fetch destination  
  
      - name: Push changes to destination repository  
        run: |  
          git push destination HEAD:main  
