name: Mirror Repos

on: 
  workflow_dispatch:
  push:  
    branches:  
      - main  
  schedule:  
    - cron: "*/10 * * * *"  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repository
        uses: actions/checkout@v2
        with:
          repository: melilace/DatabricksPrimaryRepo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: primary
      - name: Checkout Secondary repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/melilace/DatabricksSecondaryRepo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: secondary
          ref: main

      - name: Update Secondary from Primary
        run: |
          cp -r primary/* secondary/
                          
      - name: Commit and push changes
        run: |
          cd secondary
          git config --global user.name 'melilace'
          git config --global user.email 'melilace@microsoft.com'
          git add .
          git commit -m "Sync from primary"
          git push
