git clone --mirror https://github.com/melilace/DatabricksPrimaryRepo.git

cd REPOSITORY-TO-MIRROR
git remote set-url --push origin https://github.com/melilace/DatabricksSecondaryRepo.git

git fetch -p origin
git push --mirror
