name: Mirror Repos  
  
on:  
  push:  
    branches:  
      - main  
  schedule:  
    - cron: "*/10 * * * *"  
  
jobs:  
  sync:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout source repository  
        run: |  
          git clone --mirror https://github.com/melilace/DatabricksPrimaryRepo.git  
          cd DatabricksPrimaryRepo  
          git remote set-url --push origin https://github.com/melilace/DatabricksSecondaryRepo.git  
          git fetch -p origin  
          git push --mirror  
