---
name: Push Code to GitHub
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 8 * * *
    - cron: 0 12 * * *
    - cron: 0 22 * * *
jobs:
  push-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repository
        uses: actions/checkout@v2
        with:
          repository: melilace/DatabricksPrimaryRepo
          ref: main
      - name: Checkout secondary repository
        uses: actions/checkout@v2
        with:
          repository: melilace/DatabricksSecondaryRepo
          path: secondary-repo
          ref: main
      - name: Run build script
        run: ./build.sh
      - name: Run tests
        run: ./test.sh
      - name: Commit and push changes to secondary repository
        run: |
          cd secondary-repo  
          git config --global user.name 'melilace'  
          git config
