name: Mirror Repos

on:  
  push:  
    branches:  
      - main  
  schedule:  
    - cron: "*/10 * * * *"  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout primary repository
        uses: actions/checkout@v2
        with:
          repository: melilace/DatabricksPrimaryRepo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up secondary repository
        run: |
          git remote set-url --push origin https://github.com/melilace/DatabricksSecondaryRepo.git
          git fetch -p origin

      - name: Push to secondary repository
        run: git push --mirror
        env:
          GITHUB_TOKEN: ${{ secrets.MLSECRET }}
